server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todolist
    username: chunhou
    password:
  jpa:
    hibernate:
      format_sql: true
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false
    change-log: classpath:liquibase/db.changelog-master.xml
  session:
    timeout: 5m
    store-type: redis
  redis:
    host: localhost
    port: 6379
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
logging:
  level:
    org:
      thymeleaf: DEBUG

